### ISSUE TITLE
QtWebKit is deprecated

### ISSUE THREAD

**Issue by BYT3M3** [mfitzp/pyqtconfig#22]
Dear maintainer

There's an issue with qt.py. You currently import PyQt5.QtWebKit, which is deprecated. pyqtconfig still works if you have pyqt5 installed via apt or dnf (which is QT 5.9.5 for me at this moment), but not if it's installed via pip3 (which is QT 5.11.1 for me at this moment). So there needs to be some kind of way to import either PyQt5.QtWebKit and PyQt5.QtWebKitWidgets or PyQt5.QtWebEngine and  QtWebEngineWidgets, depending on PyQt5.QtCore.QT_VERSION_STR

I also have a question (which may or may not be a stupid question): why do you import everything from PyQt5.QtGui, PyQt5.QtCore, PyQt5.QtWebKit, PyQt5.QtNetwork, PyQt5.QtWidgets and PyQt5.QtWebKitWidgets? This way you have to have extra python packages installed which you don't necessarily need. Isn't there a way to do the imports as they are needed?

**Comment by mfitzp** [comment]
Thanks for this fix, I've merged and will check with latest PyQt5.

> why do you import everything ... this way you have to have extra python packages installed

The global imports were for backwards compatibility with PyQt4 which had modules arranged differently. The imports don't install anything though, you have those modules available if you've installed PyQt5.
